### ISSUE TITLE
can u create a true stretched file for new valorant patch?

### ISSUE THREAD

**Issue by lehoangvinh18022004** [TheCodingCarson/TrueStretched#1]
can u create a true stretched file for new valorant patch?

**Comment by TheCodingCarson** [comment]
Hey @lehoangvinh18022004,

**I'm currently working on the update** to patch the patch in Valorant's latest update. **With a beta releasing soon**, just working out a bug with the new method that was found in by a tester.

**Comment by lehoangvinh18022004** [comment]
youtu.be/awacsv0kITk
this is a working method somehow i found on yt

**Comment by TheCodingCarson** [comment]
> youtu.be/awacsv0kITk this is a working method somehow i found on yt

Based on how that video does it the current version should still work with it unless you need to be in Fullscreen.

**Comment by TheCodingCarson** [comment]
@lehoangvinh18022004 The beta release of 1.0.4 with 4:3 working (and any resolution) is now available. There will most likely be a beta b released before the stable version of 1.0.4.

True Stretched v1.0.4 Beta A:
[https://github.com/TheCodingCarson/TrueStretched/releases/tag/v1.0.4-beta.a](https://github.com/TheCodingCarson/TrueStretched/releases/tag/v1.0.4-beta.a)
